### ISSUE TITLE
VBA error #91 (Object variable or With block variable not set) at clsErrorBars.UseChart

### ISSUE THREAD

**Issue by bovender** [bovender/XLToolbox#463]
> This issue was submitted by the add-in's exception handler.

#### Exception:

````csharp
XLToolbox.Vba.VbaException: VBA error #91 (Object variable or With block variable not set) at clsErrorBars.UseChart
````

Message: VBA error #91 (Object variable or With block variable not set) at clsErrorBars.UseChart
#### Environment

Parameter    | Value
-------------|------
Version      | 7.2.6
OS           | Microsoft Windows NT 10.0.15014.0, 64-bit
Excel        | 365 (16.0.7668), 64-bit
CLR          | 4.0.30319.42000, 64-bit
VSTO runtime | 10.0.60301
ClickOnce    | False
Bovender     | 0.16.0.0
FreeImage    | 3.16.0

**Comment by sstanzel** [comment]
this was certainly caused by user error.  I was just clicking around to see what different features did, but of course I didn't want to see an exception

**Comment by bovender** [comment]
What did you do to produce this error? When I attempt to use the error charts function without selecting a chart first, I get a warning message, but not an error.
