### ISSUE TITLE
Ctrl Shift Arrow (left and right) key is not functioning properly

### ISSUE THREAD

**Issue by rollooo72** [bovender/XLToolbox#586]
If  I need to select the cells which has data in a row, I use to press ctrl+shift+arrow key (left or right)
In Win7 Professional Office Excel 2016, if I do the same I get an error stating "To use the Extend Chart range function, you need to have a chart!".  ctrl+shift+arrow key up or down is ok.
The problem disappears if I disable the Toolbox in the Excel advanced options.

**Comment by bovender** [comment]
You need to disable the keyboard shortcuts in the toolbox preferences. Let me know if this does not solve the problem for you!

Daniel

**Comment by rollooo72** [comment]
It worked!!!

Thanks a lot

R




2017-06-08 13:21 GMT+02:00 Daniel Kraus <notifications@github.com>:
